<?php
/**
 * Klarna Checkout extension
 *
 * @category    NWT
 * @package     NWT_KCO
 * @copyright   Copyright (c) 2015 Nordic Web Team ( http://nordicwebteam.se/ )
 * @license     http://nordicwebteam.se/licenses/nwtcl/1.0.txt  NWT Commercial License (NWTCL 1.0)
 * 
 * 
 *
 */

/**
 * Klarna Checkout sidebar template
 */
?>
<div class="kco-left body-klarna-checkout">
    <div id="nwt_checkout">
        <?php echo $this->getChildHtml(); ?>
    </div>
    <div id="nwt_overlay" style="display:none"></div>
</div>
