<script type="text/javascript">
    //<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;

    /**
     * Add agreement validation
     */
    payment.addMoreValidateFunction('checkout-agreements', function () {
        var result = true;
        if ($$('#checkout-step-payment #checkout-agreements')[0]) {
            var checkboxes = $$('#checkout-agreements input');
            for (var i = 0, l = checkboxes.length; i < l; i++) {
                if (!checkboxes[i].checked) {
                    alert("<?php echo $this->jsQuoteEscape($this->__('Please agree to all Terms and Conditions before placing the orders.')) ?>");
                    result = false;
                }
            }
        }
        return result;
    });
    //]]>
</script>
<form action="" id="co-payment-form">
    <div class="fieldset" id="checkout-payment-method-load">
        <?php echo $this->getChildChildHtml('methods_additional', '', true, true) ?>
        <?php echo $this->getChildHtml('methods') ?>
        <?php echo $this->getBlockHtml('formkey') ?>
    </div>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close">
        <a href="#" id="payment-tool-tip-close"
           title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a>
    </div>
    <div class="tool-tip-content">
        <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>"
             alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>"
             title="<?php echo $this->__('Card Verification Number Visual Reference') ?>"/>
    </div>
</div>
<?php echo $this->getChildChildHtml('additional') ?>
<div class="buttons-set" id="payment-buttons-container">
    <?php // Moved to CC form ?>
    <button type="button" id="payment-button" class="ladda-button" onclick="payment.save()" data-style="slide-up"
            data-color="jmango" data-size="s">
        <span class="ladda-label"><?php echo $this->__('Confirm order') ?></span>
    </button>
</div>
<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event) {
        if ($('payment-tool-tip')) {
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event) - 560) + 'px'
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if ($('payment-tool-tip-close')) {
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    //]]>
</script>
