<?php
/**
 * Copyright 2015 JMango360
 */
?>
<?php $layoutDir = Mage::helper('japi')->getLayoutDir() ?>
<!DOCTYPE html>
<html lang="en" dir="<?php echo $layoutDir ?>" class="<?php echo $layoutDir ?>">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php //echo $this->getChildHtml('header') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>
<?php //echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
