<?php
/**
 * Copyright 2015 JMango360
 */
?>
<?php $layoutDir = Mage::helper('japi')->getLayoutDir() ?>
<!DOCTYPE html>
<html lang="en" dir="<?php echo $layoutDir ?>" class="<?php echo $layoutDir ?>">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="<?php echo $this->getBodyClass() ?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<?php //echo $this->getChildHtml('header') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<div class="main-container">
    <div class="col-main">
        <?php echo $this->getChildHtml('content') ?>
    </div>
</div>
<?php //echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
